[variables]
NODE_VERSION = '18'
PHP_VERSION = '8.2'

[phases.setup]
nixPkgs = ['nodejs_18', 'php82', 'php82Packages.composer', 'sqlite']

[phases.install]
cmds = [
    'npm install',
    'composer install --no-dev --optimize-autoloader'
]

[phases.build]
cmds = [
    'npm run build',
    'php artisan config:cache',
    'php artisan route:cache',
    'php artisan view:cache'
]

[start]
cmd = 'php bootstrap/railway.php && php -S 0.0.0.0:$PORT -t public'
