[phases.setup]
nixPkgs = ['php82', 'php82Packages.composer', 'nodejs_18']

[phases.install]
cmds = [
    'composer install --no-dev --optimize-autoloader',
    'php artisan config:cache',
    'php artisan route:cache',
    'php artisan view:cache',
    'npm ci && npm run build'
]

[phases.build]
cmds = ['echo "Build completed"']

[start]
cmd = 'php artisan serve --host=0.0.0.0 --port=$PORT'
