import '../css/app.css';

import { createInertiaApp, type PageProps } from '@inertiajs/react';
import axios from 'axios';
import { resolvePageComponent } from 'laravel-vite-plugin/inertia-helpers';
import React from 'react';
import { createRoot } from 'react-dom/client';
import { initializeTheme } from './hooks/use-appearance';

const appName = import.meta.env.VITE_APP_NAME || 'Cahaya Anbiya';

if (typeof window !== 'undefined') {
    const csrfToken = document.querySelector<HTMLMetaElement>('meta[name="csrf-token"]')?.content;

    if (csrfToken) {
        axios.defaults.headers.common['X-CSRF-TOKEN'] = csrfToken;
    }

    axios.defaults.withCredentials = true;
    
    // CRITICAL: Force HTTPS for all URLs BEFORE Inertia app is created
    // This prevents Mixed Content errors where HTTPS page tries to make HTTP requests
    if (window.location.protocol === 'https:') {
        // Override Ziggy route() function to always return HTTPS URLs
        if (typeof window !== 'undefined' && (window as any).Ziggy) {
            const ziggy = (window as any).Ziggy;
            if (ziggy.url && ziggy.url.startsWith('http://')) {
                ziggy.url = ziggy.url.replace('http://', 'https://');
            }
            
            // Override route function to force HTTPS
            const originalRoute = (window as any).route;
            if (originalRoute) {
                (window as any).route = function(name: string, params?: any, absolute?: boolean, config?: any) {
                    const url = originalRoute(name, params, absolute, config);
                    if (typeof url === 'string' && url.startsWith('http://')) {
                        return url.replace('http://', 'https://');
                    }
                    return url;
                };
            }
        }
        
        // Override fetch to force HTTPS
        const originalFetch = window.fetch;
        window.fetch = function(url: RequestInfo | URL, options?: RequestInit) {
            if (typeof url === 'string' && url.startsWith('http://')) {
                url = url.replace('http://', 'https://');
            } else if (url instanceof Request && url.url.startsWith('http://')) {
                url = new Request(url.url.replace('http://', 'https://'), url);
            }
            return originalFetch(url, options);
        };
        
        // Override XMLHttpRequest to force HTTPS
        const originalXHROpen = XMLHttpRequest.prototype.open;
        XMLHttpRequest.prototype.open = function(method: string, url: string | URL, ...args: any[]) {
            if (typeof url === 'string' && url.startsWith('http://')) {
                url = url.replace('http://', 'https://');
            }
            return originalXHROpen.call(this, method, url, ...args);
        };
    }
}

// Force HTTPS for all requests to prevent Mixed Content errors
if (typeof window !== 'undefined' && window.location.protocol === 'https:') {
    // Override fetch to force HTTPS
    const originalFetch = window.fetch;
    window.fetch = function (url, options) {
        if (typeof url === 'string' && url.startsWith('http://')) {
            url = url.replace('http://', 'https://');
        } else if (url instanceof Request && url.url.startsWith('http://')) {
            url = new Request(url.url.replace('http://', 'https://'), url);
        }

        return originalFetch(url as RequestInfo | URL, options);
    };

    // Override XMLHttpRequest to force HTTPS
    const originalXHROpen = XMLHttpRequest.prototype.open;
    XMLHttpRequest.prototype.open = function (method, url, ...args) {
        if (typeof url === 'string' && url.startsWith('http://')) {
            url = url.replace('http://', 'https://');
        }
        return originalXHROpen.call(this, method, url, ...args);
    };
}

// Add global error handler for unhandled errors
if (typeof window !== 'undefined') {
    window.addEventListener('error', (event) => {
        console.error('Global error:', event.error);
    });
    
    window.addEventListener('unhandledrejection', (event) => {
        console.error('Unhandled promise rejection:', event.reason);
    });
}

// CRITICAL: Override Ziggy route() function BEFORE Inertia app is created
// This ensures all URLs generated by Inertia use HTTPS
if (typeof window !== 'undefined' && window.location.protocol === 'https:') {
    // Wait for Ziggy to be loaded, then override route function
    const overrideRouteFunction = () => {
        if (typeof (window as any).Ziggy !== 'undefined') {
            const ziggy = (window as any).Ziggy;
            if (ziggy.url && ziggy.url.startsWith('http://')) {
                ziggy.url = ziggy.url.replace('http://', 'https://');
            }
            
            // Override route function to force HTTPS
            const originalRoute = (window as any).route;
            if (originalRoute && typeof originalRoute === 'function') {
                (window as any).route = function(name: string, params?: any, absolute?: boolean, config?: any) {
                    const url = originalRoute(name, params, absolute, config);
                    if (typeof url === 'string' && url.startsWith('http://')) {
                        return url.replace('http://', 'https://');
                    }
                    return url;
                };
            }
        } else {
            // Ziggy not loaded yet, try again after a short delay
            setTimeout(overrideRouteFunction, 50);
        }
    };
    
    // Try to override immediately, and also after DOMContentLoaded
    overrideRouteFunction();
    if (document.readyState === 'loading') {
        document.addEventListener('DOMContentLoaded', overrideRouteFunction);
    }
}

// Wrap entire Inertia app creation in try-catch for safety
let inertiaAppCreated = false;

try {
    createInertiaApp({
    title: (title) => {
        try {
            return title ? `${title} - ${appName}` : appName;
        } catch {
            return appName;
        }
    },
    resolve: (name) => {
        // All pages use dynamic import for optimal code splitting
        const pages = import.meta.glob('./pages/**/*.tsx', { eager: false });
        return resolvePageComponent(`./pages/${name}.tsx`, pages)
            .then((module: unknown) => {
                if (!module) {
                    console.error(`Module not found for page: ${name}`);
                    throw new Error(`Page component not found: ${name}`);
                }
                const Page = (module as { default: React.ComponentType<PageProps> })?.default;
                if (!Page) {
                    console.error(`Page component default export not found for: ${name}`, module);
                    throw new Error(`Page component default export not found: ${name}`);
                }
                // Return page directly without heavy animation wrapper
                // Individual pages can add their own animations if needed
                return Page;
            })
            .catch((error) => {
                console.error(`Failed to load page component: ${name}`, error);
                // Return a fallback error page
                const ErrorPage = () => (
                    <div className="flex min-h-screen items-center justify-center bg-gray-50">
                        <div className="text-center">
                            <h1 className="text-2xl font-bold text-gray-900">Page Not Found</h1>
                            <p className="mt-2 text-gray-600">The page "{name}" could not be loaded.</p>
                            <p className="mt-1 text-sm text-gray-500">Error: {error instanceof Error ? error.message : String(error)}</p>
                            <button
                                onClick={() => (window.location.href = '/')}
                                className="mt-4 rounded-md bg-blue-600 px-4 py-2 text-white hover:bg-blue-700"
                            >
                                Go Home
                            </button>
                        </div>
                    </div>
                );
                return ErrorPage;
            });
    },
    setup({ el, App, props }) {
        // Enhanced logging for debugging
        if (typeof window !== 'undefined') {
            console.log('[Inertia] Setup called', { 
                hasEl: !!el, 
                hasApp: !!App, 
                hasProps: !!props,
                elId: el?.id,
                elTag: el?.tagName
            });
        }
        
        if (!el) {
            console.error('[Inertia] No element provided to Inertia setup');
            // Try to find the element - Inertia creates element with data-page attribute
            const fallbackEl = document.querySelector('[data-page]') || document.getElementById('app');
            if (fallbackEl) {
                console.log('[Inertia] Found fallback element, using it');
                el = fallbackEl as HTMLElement;
            } else {
                console.error('[Inertia] No fallback element found, creating one');
                // Last resort: create the element
                const newEl = document.createElement('div');
                newEl.id = 'app';
                document.body.appendChild(newEl);
                el = newEl;
                console.log('[Inertia] Created new app element');
            }
        }
        
        try {
            if (typeof window !== 'undefined') {
                console.log('[Inertia] Creating React root...');
            }
            const root = createRoot(el);
            
            // Wrap in try-catch to prevent white screen on render errors
            try {
                if (typeof window !== 'undefined') {
                    console.log('[Inertia] Rendering app...', { 
                        propsKeys: Object.keys(props || {}),
                        propsType: typeof props
                    });
                }
                
                // Ensure App and props are valid
                if (!App) {
                    throw new Error('App component is undefined');
                }
                
                root.render(<App {...(props || {})} />);
                
                if (typeof window !== 'undefined') {
                    console.log('[Inertia] App rendered successfully');
                }
            } catch (error) {
                console.error('[Inertia] Error rendering app:', error);
                console.error('[Inertia] Error stack:', error instanceof Error ? error.stack : 'No stack');
                
                // Render fallback UI with more details
                try {
                    root.render(
                        <div style={{ 
                            padding: '2rem', 
                            textAlign: 'center',
                            backgroundColor: '#f9fafb',
                            minHeight: '100vh',
                            display: 'flex',
                            flexDirection: 'column',
                            alignItems: 'center',
                            justifyContent: 'center'
                        }}>
                            <h1 style={{ fontSize: '1.5rem', fontWeight: 'bold', marginBottom: '1rem', color: '#111827' }}>
                                Application Error
                            </h1>
                            <p style={{ color: '#6b7280', marginBottom: '0.5rem' }}>
                                Something went wrong. Please refresh the page.
                            </p>
                            <p style={{ 
                                fontSize: '0.875rem', 
                                color: '#9ca3af', 
                                marginTop: '1rem',
                                fontFamily: 'monospace',
                                backgroundColor: '#f3f4f6',
                                padding: '0.5rem',
                                borderRadius: '0.25rem',
                                maxWidth: '600px',
                                wordBreak: 'break-word'
                            }}>
                                Error: {error instanceof Error ? error.message : String(error)}
                            </p>
                            <button 
                                onClick={() => window.location.reload()}
                                style={{ 
                                    marginTop: '1.5rem', 
                                    padding: '0.75rem 1.5rem', 
                                    backgroundColor: '#3b82f6', 
                                    color: 'white', 
                                    border: 'none', 
                                    borderRadius: '0.375rem',
                                    cursor: 'pointer',
                                    fontSize: '1rem',
                                    fontWeight: '500'
                                }}
                            >
                                Refresh Page
                            </button>
                        </div>
                    );
                } catch (renderError) {
                    console.error('[Inertia] Error rendering fallback UI:', renderError);
                }
            }
        } catch (error) {
            console.error('[Inertia] Fatal error setting up app:', error);
            console.error('[Inertia] Error stack:', error instanceof Error ? error.stack : 'No stack');
            
            // Last resort: show error in the element using innerHTML
            if (el) {
                try {
                    el.innerHTML = `
                        <div style="padding: 2rem; text-align: center; background-color: #f9fafb; min-height: 100vh; display: flex; flex-direction: column; align-items: center; justify-content: center;">
                            <h1 style="font-size: 1.5rem; font-weight: bold; margin-bottom: 1rem; color: #111827;">Application Error</h1>
                            <p style="color: #6b7280; margin-bottom: 0.5rem;">Something went wrong. Please refresh the page.</p>
                            <p style="font-size: 0.875rem; color: #9ca3af; margin-top: 1rem; font-family: monospace; background-color: #f3f4f6; padding: 0.5rem; border-radius: 0.25rem; max-width: 600px; word-break: break-word;">
                                Error: ${error instanceof Error ? error.message.replace(/</g, '&lt;').replace(/>/g, '&gt;') : String(error).replace(/</g, '&lt;').replace(/>/g, '&gt;')}
                            </p>
                            <button 
                                onclick="window.location.reload()"
                                style="margin-top: 1.5rem; padding: 0.75rem 1.5rem; background-color: #3b82f6; color: white; border: none; border-radius: 0.375rem; cursor: pointer; font-size: 1rem; font-weight: 500;"
                            >
                                Refresh Page
                            </button>
                        </div>
                    `;
                } catch (innerHTMLError) {
                    console.error('[Inertia] Error setting innerHTML:', innerHTMLError);
                }
            }
        }
    },
    progress: {
        color: '#BC8E2E',
    },
    onError: (error) => {
        // Don't handle validation errors here - they should be displayed in the form
        // Validation errors (422) are handled by Inertia automatically and displayed via InputError components
        const errorStatus = (error as any)?.status;
        const errorMessage = error?.message || (typeof error === 'string' ? error : '') || '';
        const errorString = JSON.stringify(error || {});
        
        // Skip handling for validation errors (422) - let them display in form
        if (errorStatus === 422 || errorString.includes('422')) {
            console.log('[Inertia] Validation error - will be displayed in form');
            return; // Let Inertia handle validation errors normally
        }
        
        // Handle 419 Page Expired errors
        if (
            errorStatus === 419 ||
            errorMessage.includes('419') || 
            errorMessage.includes('expired') || 
            errorMessage.includes('PAGE EXPIRED') ||
            errorString.includes('419') ||
            errorString.includes('expired')
        ) {
            console.warn('[Inertia] CSRF token expired, reloading page...');
            // Reload page to refresh CSRF token
            setTimeout(() => {
                window.location.reload();
            }, 500);
            return;
        }
        
        // Handle 500 Server Errors
        if (
            errorStatus === 500 ||
            errorMessage.includes('500') ||
            errorMessage.includes('SERVER ERROR') ||
            errorString.includes('500')
        ) {
            console.error('[Inertia] Server error occurred:', error);
            // Show user-friendly message and reload
            if (confirm('A server error occurred. Would you like to refresh the page?')) {
                window.location.reload();
            }
            return;
        }
        
        // Log other errors for debugging
        console.error('[Inertia] Unhandled error:', error);
    },
    });
    
    inertiaAppCreated = true;
    console.log('[App] Inertia app created successfully');
} catch (error) {
    console.error('[App] Fatal error creating Inertia app:', error);
    console.error('[App] Error stack:', error instanceof Error ? error.stack : 'No stack');
    
    // Last resort: show error message
    if (typeof window !== 'undefined' && typeof document !== 'undefined') {
        const errorDiv = document.createElement('div');
        errorDiv.id = 'app-error';
        errorDiv.style.cssText = 'padding: 2rem; text-align: center; background-color: #f9fafb; min-height: 100vh; display: flex; flex-direction: column; align-items: center; justify-content: center;';
        errorDiv.innerHTML = `
            <h1 style="font-size: 1.5rem; font-weight: bold; margin-bottom: 1rem; color: #111827;">Application Error</h1>
            <p style="color: #6b7280; margin-bottom: 0.5rem;">Failed to initialize application.</p>
            <p style="font-size: 0.875rem; color: #9ca3af; margin-top: 1rem; font-family: monospace; background-color: #f3f4f6; padding: 0.5rem; border-radius: 0.25rem; max-width: 600px; word-break: break-word;">
                Error: ${error instanceof Error ? error.message.replace(/</g, '&lt;').replace(/>/g, '&gt;') : String(error).replace(/</g, '&lt;').replace(/>/g, '&gt;')}
            </p>
            <button 
                onclick="window.location.reload()"
                style="margin-top: 1.5rem; padding: 0.75rem 1.5rem; background-color: #3b82f6; color: white; border: none; border-radius: 0.375rem; cursor: pointer; font-size: 1rem; font-weight: 500;"
            >
                Refresh Page
            </button>
        `;
        document.body.appendChild(errorDiv);
    }
}

// This will set light / dark mode on load...
// Wrap in try-catch to prevent errors from breaking the app
if (inertiaAppCreated) {
    try {
        if (typeof window !== 'undefined') {
            initializeTheme();
        }
    } catch (error) {
        console.error('[App] Error initializing theme:', error);
        // Don't throw - theme initialization failure shouldn't break the app
    }
}
